# Generated by Django 5.1.4 on 2025-01-18 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('level', models.IntegerField(default=1)),
                ('picture', models.ImageField(null=True, upload_to='pokemon_images')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('P', 'PLANTA'), ('L', 'LAGARTIJA'), ('A', 'AGUA'), ('E', 'ELECTRICO'), ('T', 'TIERRA'), ('F', 'FUEGO')], max_length=30)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=7)),
                ('height', models.DecimalField(decimal_places=4, max_digits=7)),
                ('picture', models.ImageField(upload_to='pokemon_images')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pokedex.trainer')),
            ],
        ),
    ]
