# Generated by Django 5.1.4 on 2025-01-10 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='pokedex.trainer'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'AGUA'), ('P', 'PLANTA'), ('T', 'TIERRA'), ('E', 'ELECTRICO'), ('L', 'LAGARTIJA'), ('F', 'FUEGO')], max_length=30),
        ),
    ]
