# Generated by Django 5.1.4 on 2025-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_pokemon_trainer_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'ELECTRICO'), ('P', 'PLANTA'), ('F', 'FUEGO'), ('L', 'LAGARTIJA'), ('T', 'TIERRA'), ('A', 'AGUA')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
